# Generated by Django 5.1.6 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=255)),
                ("query_norm", models.CharField(db_index=True, max_length=255)),
                ("mode", models.CharField(choices=[("title", "title"), ("ingredient", "ingredient")], db_index=True, default="title", max_length=32)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["mode", "query_norm", "-created_at"], name="meds_search_mode_36f53e_idx"),
                    models.Index(fields=["session_key", "-created_at"], name="meds_search_sessio_71b604_idx"),
                ],
            },
        ),
    ]

